services:
  bot:
    build: .
    volumes:
      - type: bind
        source: config.json
        target: /usr/src/app/config.json

      - type: bind
        source: data
        target: /usr/src/app/data
